hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

hw_project/quotes/urls.py
from django.urls import path, include

from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='root'),  
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<str:author_id>', views.author_about, name='author_about'),
    path('tag/<str:tag_name>/', views.tag_page, name='tag_page'),
    path('author_for_tag/<int:author_id>', views.author_for_tag, name='author_for_tag'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_tag/', views.add_tag, name='add_tag'),
   ]

hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

hw_project/quotes/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
  
    
class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def __str__(self):
        return f"{self.name}"
   
class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)   

hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, ModelChoiceField, ModelMultipleChoiceField, SelectMultiple, Select, Textarea, ChoiceField

from .models import Tag, Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_date = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(required=True, widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by('name'), widget=SelectMultiple(attrs={"class": "form-select", "size": "7"}))
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'] = ChoiceField(
            choices=self.get_author_choices(),
            widget=Select(attrs={"class": "form-select"})
        )

    def get_author_choices(self):
        authors = Author.objects.all().order_by('fullname')
        choices = [(author.id, author.fullname) for author in authors]
        return choices

    class Meta:
        model = Quote
        fields = ['quote', 'author']
    

hw_project/quotes/views.py
from django.shortcuts import render, redirect
from .utils import get_mongodb
from django.core.paginator import Paginator
from bson.objectid import ObjectId
from .models import Quote, Tag, Author
from .forms import QuoteForm, AuthorForm, TagForm
from django.contrib.auth.decorators import login_required
from django.db.models import Count


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    print(list(quotes))
    latest_quote = Quote.objects.latest('created_at')
    tags_for_latest_quote = latest_quote.tags.all()
    author_for_latest_quote = Author.objects.get(id=latest_quote.author_id)
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    for i, tag in enumerate(top_tags, start=1):
        tag.css_class = f'tag-{i}'  # Создаем классы вида tag-1, tag-2 и т.д.
    return render(request, 'quotes/index.html', context={'quotes':quotes_on_page, 
                                                         'latest_quote': latest_quote,
                                                          'author_for_latest_quote': author_for_latest_quote, 
                                                          'tags_for_latest_quote': tags_for_latest_quote,
                                                          'top_tags': top_tags,
                                                          })

def author_about(request, author_id):
    db = get_mongodb()
    author = db.authors.find_one({'_id': ObjectId(author_id)})  # Використання ObjectId(author_id)
    return render(request, 'quotes/author.html', context={'author': author})

def tag_page(request, tag_name):
    tag = Tag.objects.get(name=tag_name)
    quotes_with_tag = Quote.objects.filter(tags=tag)
    return render(request, 'quotes/tag.html', {'quotes_with_tag': quotes_with_tag, 'tag': tag})


def author_for_tag(request, author_id):
    author = Author.objects.get(id=author_id)
    return render(request, 'quotes/author_for_tag.html', context={'author': author})


@login_required  # Проверяет, что пользователь авторизован, прежде чем позволить доступ к представлению.
def add_author(request):  # Обработчик запроса для добавления нового автора.
    if request.method == 'POST':  # Проверка метода запроса (POST или GET).
        form = AuthorForm(request.POST)  # Создание формы на основе POST данных.
        if form.is_valid():  # Проверка валидности данных из формы.
            new_author = form.save(commit=False)  # Создание нового автора без сохранения в БД.
            new_author.user = request.user  # Установка пользователя как создателя автора.
            new_author.save()  # Сохранение автора в БД.
            return redirect(to='quotes:root')  # Перенаправление на главную страницу.
        else:
            return render(request, 'quotes/add_author.html', context={'form': form})  # Отображение формы с ошибками валидации.
    return render(request, 'quotes/add_author.html', context={'form': AuthorForm()})  # Отображение пустой формы для ввода.


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            tag_name = form.cleaned_data["tags"]
            for tag in tag_name:
                new_quote.tags.add(tag.id)
            new_quote.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_quote.html', context={'form': form})
    return render(request, 'quotes/add_quote.html', context={'form': QuoteForm()})


@login_required
def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/add_tag.html', context={'form': form})
    return render(request, 'quotes/add_tag.html', context={'form': TagForm()})

hw_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Add Author</h1>

{% if form.errors %}
    <div class="alert alert-danger" role="alert">
        <strong>Oops! Something went wrong:</strong>
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endif %}

<form action="{% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Fullname</label>
        {{form.fullname}}
    </div>

    <div class="mb-3">
        <label class="form-label">Date of Birth</label>
        {{form.born_date}}
    </div>

    <div class="mb-3">
        <label class="form-label">Place of Birth</label>
        {{form.born_location}}
    </div>

   <div class="mb-3">
        <label class="form-label">Description</label>
       {{form.description}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<h1>Add Quote</h1>
<form action="{% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Quote</label>
        {{form.quote}}
    </div>

    <div class="mb-3">
        <label class="form-label">Author</label>
        {{form.author}}
    </div>

    <div class="mb-3">
        <label class="form-label">Tags</label>
        {{form.tags}}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %} 

hw_project/quotes/templates/quotes/add_tag.html
{% extends "quotes/base.html" %}

{% block content %}
<h1>Add Tag</h1>
<form action="{% url 'quotes:add_tag' %}" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Tag</label>
        {{form.name}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div>
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
    
  
</div>
{% endblock %}

hw_project/quotes/templates/quotes/author_for_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
<div>
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
    
  
</div>
{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary mr-4">Add Author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary mr-4">Add Quote</a>
                    <a href="{% url 'quotes:add_tag' %}" class="btn btn-primary mr-4">Add Tag</a>
                   
                    <form id="logout-form" action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="logout" id="logout-button" style="font-size: 18px; margin-top: 32px; padding: 2px 4px; border-radius: 5px; color: white; background-color: hsl(345, 2%, 40%);">Logout</button>

                       
                    </form>
                    {% else %}
                        <a href="{% url 'users:signup' %}" class="btn btn-primary mr-4">SignUp</a>
                        <a href="{% url 'users:signin' %}" class="btn btn-primary mr-4">SignIn</a>
                    {% endif %}   
                    
                    
                
                </p>
            </div>
        </div>
        {% block content %}    {% endblock %}
    </div>

       
    
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}



{% block content %}


 
<div class="row">
    <div class="col-md-8">

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text"> {{latest_quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{author_for_latest_quote.fullname}}</small>
               
                <a href="/author_for_tag/{{latest_quote.author.id}}">  (about)</a>
                   
            </span>
            <div class="tags">
                Tags:
                {% for tag in tags_for_latest_quote %}       
                <a class="tag" href="/tag/{{ tag.name }}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>    
        
    {% for quote in quotes %}
    
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
           
            <a href="/author/{{quote.author}}">  (about)</a>
           


        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags %}            
            <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
            {% endfor %}
        </div>
    </div>


    
    {% endfor %}

        
        
    <nav>
        <ul class="pager">
            
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}" 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"><span aria-hidden="true">←</span> Previous</a>
            </li>
            
            
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
            
            
        </ul>
    </nav>
    </div>

    <div class="col-md-4 tags-box">
        
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        
       
        <span class="tag-item">
        <a class="{{ tag.css_class }}" href="/tag/{{tag}}">{{tag}}</a>
        </span>
        {% endfor %}

</div>



</div>

{% endblock %}

hw_project/quotes/templates/quotes/login.html
{% extends "quotes/base.html" %}

{% block content %}
    {% if messages %}
        <div>
            {% for message in messages %}
                <div {% if message.tags %} class="alert- {{ message.tags }}" {% endif %}>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}

    <form action="{% url 'quotes:Login' %}" method="post">
        {% csrf_token %}
        <div>
            <label>Ім'я користувача: {{ form.username }}</label>
        </div>
        <div>
            <label>Пароль: {{ form.password }}</label>
        </div>
        <div class="grid">
            <button type="submit">Надіслати</button>
            <button type="reset" class="secondary">Скинути</button>
        </div>
    </form>
{% endblock %}

hw_project/quotes/templates/quotes/password_reset.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hw_project/quotes/templates/quotes/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_project/quotes/templates/quotes/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'quotes:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

hw_project/quotes/templates/quotes/tag.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h3>Viewing tag: {{ tag.name }}</h3>
    {% for quote in quotes_with_tag %}
        <div class="quote">
            <p>{{ quote.quote }}</p>
            <p>by {{ quote.author.fullname }} <a href="/author_for_tag/{{quote.author.id}}">  (about)</a>



            <p>Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>

                {% endfor %}
            </p>
        </div>
    {% endfor %}
{% endblock %}